version: '3.5'

services:
  chat-postgres:
    container_name: chat-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - "/Applications/PostgreSQL 16:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  chat-backend:
    container_name: chat-backend
    image: backend_app:dev
    ports:
      - "3333:3333"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
